version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=airlines
      - POSTGRES_USER=airline_user
      - POSTGRES_PASSWORD=password
  web:
    build:
      dockerfile: docker/dev/Dockerfile
      context: ../..
    volumes:
      - ../..:/airlines
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
        python manage.py runserver 0.0.0.0:8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - db

volumes:
  pg_data: